version: '3.7'

services:
            
    ssh_honeypot:
        container_name: ssh_honeypot
        build:
          context: .
          dockerfile: Dockerfile
        image: basic_ssh_honeypot
        tty: true  
        command: python ssh_honeypot.py --port 2222
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        ports:
            - 2224:2222
        environment:
            - CHOKIDAR_USEPOLLING=true
            
    ssh_honeypot_downloader:
        container_name: ssh_honeypot_downloader
        build:
          context: .
          dockerfile: Dockerfile
        image: ssh_honeypot_downloader
        tty: true  
        command: python ssh_honeypot_downloader.py
        volumes:
            - .:/usr/src/app
        env_file:
            - ./.env
        environment:
            - CHOKIDAR_USEPOLLING=true
            
    ssh_honeypot_redis_db:
        container_name: ssh_honeypot_redis_db
        image: redis:6.0.7-alpine
        command: redis-server --requirepass password 
        env_file:
            - ./.env
